openapi: 3.0.0
info:
  description: |
    pokemon status and damage calculate api
    
    for short pca server
  version: 1.0.0
  title: OpenAPI pca server
tags:
  - name: status
    description: Everything about pokemon status
paths:
  '/status/{pokeId}':
    get:
      tags:
        - status
      summary: Find PokemonStatus by ID
      description: Returns a single PokemonStatus
      operationId: pokeId
      parameters:
        - name: pokeId
          in: path
          description: ID of PokemonStatus to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/PokemonStatus'
            application/json:
              schema:
                $ref: '#/components/schemas/PokemonStatus'
        '400':
          description: Invalid ID supplied
        '404':
          description: PokemonStatus not found
components:
  requestBodies:
    PokemonStatus:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PokemonStatus'
        application/xml:
          schema:
            $ref: '#/components/schemas/PokemonStatus'
      description: PokemonStatus
      required: true
  schemas:
    PokemonStatus:
      title: PokemonStatus
      description: PokemonStatus
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          pattern: '^[a-zA-Z0-9]+[a-zA-Z0-9\.\-_]*[a-zA-Z0-9]+$'
      xml:
        name: PokemonStatus
