/*
 * OpenAPI pca server
 *
 * pokemon status and damage calculate api  for short pca server 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// PokemonStatus
type PokemonStatus struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`
}
